# Traefik 
- name: Creates needed traefik dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0744'
  loop:
    - /home/{{ user }}/traefik
    - /etc/traefik
    - /etc/traefik/certs

- name: Copy Traefik config file
  copy:
    src: traefik/config/traefik.yml
    dest: /etc/traefik/traefik.yml
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0744'
