version: '3'

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      #- "8080:8080"  # Don't do this in production!
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-ssl-certs:/ssl-certs

  uptime:
    image: louislam/uptime-kuma
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.uptime.entrypoints: "websecure"
      traefik.http.routers.uptime.rule: "Host(`uptime.bartelloni.it`)"
      traefik.http.routers.uptime.tls: true
      traefik.http.routers.uptime.tls.certresolver: "production"
    volumes:
      - uptime-kuma:/app/data

volumes:
   uptime-kuma:
   firefly_iii_upload:
   firefly_iii_db:
   traefik-ssl-certs:
       driver: local
